### ISSUE TITLE
Getting unknownhostexception

### ISSUE THREAD

**Issue by pgurani123** [alexsaves/acs-apiclient-java#10]
Hi,

I am trying to access foresee endpoints using the api but I am getting exceptions. I have tried using both spring security as well your API. Can you help me out in what could be the issue? 

exception stack trace - 

java.net.UnknownHostException: portal2.foreseeresults.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.foresee.http.ResponseImp.getBody(ResponseImp.java:65)
	at com.foresee.auth.AcsApiClient.ParseGetTokenResponse(AcsApiClient.java:188)
	at com.foresee.auth.AcsApiClient.InitializeOAuth(AcsApiClient.java:316)
	at com.pod.ApiTest.main(ApiTest.java:122)
 

The code - 
private static ResponseImp MakeCurrentUserRequest(AcsApiClient apiClient){
		try{
			String getTarget = "https://portal2.foreseeresults.com/services/currentUser/";

			String authorizeSignature = apiClient.getSignedUrl(OAuthMessage.GET, getTarget);
		//	String postTarget = "https://www.services.answerscloud.com/services/oauth/user_authorization";
			RequestAbstraction request = new RequestBuilderImp().builder().withUrl(getTarget)
					.withHeader("Authorization", authorizeSignature).build();
			ClientAbstraction client = new ClientBuilderImp().create();
			ResponseImp resp =  (ResponseImp) client.newCall(request).execute();
			return resp;
		}catch(Exception exc){
			exc.printStackTrace();
			return null;
		}
	}

	public static void main(String[] args){
		AcsApiClientConfig config = new AcsApiClientConfig(
			"***************", "***************", "***************", "***************");
			
		AcsApiClient apiClient = new AcsApiClient(config, new ClientBuilderImp(), new RequestBuilderImp(), new PostBodyBuilderImp(), null);
				apiClient.InitializeOAuth();
			ResponseImp response = MakeCurrentUserRequest(apiClient);
		}

**Comment by battewr** [comment]
The code copied and pasted into my solution works.

Can you confirm using a tool like nslookup that your computer receives a DNS response for portal2.foreseerestuls.com.  Something like:
Name:    portal2.foreseeresults.com.lb.foreseeresults.com
Address:  67.216.181.238
Aliases:  portal2.foreseeresults.com

**Comment by battewr** [comment]
Here's the complete transposed sample/example:
package com.foresee.demo;

import com.foresee.absImpl.logging.LoggerImp;
import com.foresee.auth.AcsApiClient;
import com.foresee.auth.AcsApiClientConfig;
import com.foresee.auth.oauth.OAuthMessage;
import com.foresee.auth.oauth.signature.OAuthSignatureMethod;
import com.foresee.http.ClientBuilderImp;
import com.foresee.http.PostBodyBuilderImp;
import com.foresee.http.RequestBuilderImp;
import com.foresee.http.ResponseImp;
import com.foresee.interfaces.http.ClientAbstraction;
import com.foresee.interfaces.http.RequestAbstraction;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class Main {
    private static ResponseImp MakeCurrentUserRequest(AcsApiClient apiClient) {
        try {
            String getTarget = "https://portal2.foreseeresults.com/services/currentUser/";

            String authorizeSignature = apiClient.getSignedUrl(OAuthMessage.GET, getTarget);
            //  String postTarget = "https://www.services.answerscloud.com/services/oauth/user_authorization";
            RequestAbstraction request = new RequestBuilderImp().builder().withUrl(getTarget)
                    .withHeader("Authorization", authorizeSignature).build();
            ClientAbstraction client = new ClientBuilderImp().create();
            ResponseImp resp = (ResponseImp) client.newCall(request).execute();
            return resp;
        } catch (Exception exc) {
            exc.printStackTrace();
            return null;
        }
    }

    public static void main(String[] args) {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        AcsApiClientConfig config = new AcsApiClientConfig(...);


        AcsApiClient apiClient = new AcsApiClient(config, new ClientBuilderImp(), new RequestBuilderImp(), new PostBodyBuilderImp(), new LoggerImp());
        apiClient.InitializeOAuth();
        ResponseImp response = MakeCurrentUserRequest(apiClient);
        System.out.println(response.getBody().asString());

    }
}

**Comment by battewr** [comment]
Output is a single line with logging being null (I used your keys and passwords, so the results are anonimized):

{"links":[{"rel":"self","href":"https://portal2.foreseeresults.com/services/currentUser"},{"rel":"user","href":"https://portal2.foreseeresults.com/services/clients/*****/users/****"},{"rel":"client","href":"https://portal2.foreseeresults.com/services/clients/*****"}],"userId":*****,"username":"******","firstName":"****","lastName":"****","clientId":*****,"passwordExpiryDate":"2016-01-15","grantedAuthorities":[{"authority":"ADHOC"},{"authority":"ADHOC_CROSS_TAB"},{"authority":"ADHOC_RESPONDENTS"},{"authority":"ADHOC_SAT_COMPARE"},{"authority":"ADVANCED_ANALYTICS"},{"authority":"CALL-CENTER"},{"authority":"CLIENT_REPORTING"},{"authority":"COMMENT CLUSTER"},{"authority":"E-MAIL"},{"authority":"HRRCHY_ACCESS"},{"authority":"IMPACT_CALCULATOR"},{"authority":"IN-STORE"},{"authority":"MOBILE"},{"authority":"MULTI_MEASURE"},{"authority":"P3_ACCESS"},{"authority":"P3_DASHBOARD_SHARE"},{"authority":"PORTAL"},{"authority":"PORTAL_ACTIVITY"},{"authority":"PORTAL_DETAILS"},{"authority":"PORTAL_OPEN_ENDS"},{"authority":"PORTAL_PRIORITY"},{"authority":"PORTAL_QUESTIONS"},{"authority":"PORTAL_SAT_SUMMARY"},{"authority":"PORTAL_SUMMARY"},{"authority":"POST_EXPERIENCE"},{"authority":"RESEARCH"},{"authority":"WEB"},{"authority":"WOMI"},{"authority":"WORKSPACE"}],"consumerAuthorities":[{"authority":"API_TIER_2"}]}

**Comment by pgurani123** [comment]
hi,

yes I tried this on my residential network and it works. Seems like a firewall issue from the company's network. Thanks a lot for your help
