### ISSUE TITLE
Post Call Returning 400 Error

### ISSUE THREAD

**Issue by taruntrehan** [alexsaves/acs-apiclient-java#14]
Hi,
I am trying to do a HTTP post method on a URL and it is returning 400 error.
All other GET calls are running fine. Following is the code snippet associated.

`private static ResponseImp FetchRespondentExtract(AcsApiClient apiClient) {
                        try {
 
                        String postTargetUrl = "https://services.answerscloud.com/services/clients/CLIENTID/measures/MEASUREID/respondentsextract";
                        System.out.println("Post URL Call Is:"+postTargetUrl);
                        String authorizeSignature = apiClient.getSignedUrl(OAuthMessage.POST, postTargetUrl);
                        RequestAbstraction request = new RequestBuilderImp().builder().withUrl(postTargetUrl)
                        .withHeader("Authorization", authorizeSignature).withPostBody(new PostBodyImp("application/json",
                                    "{\"dateRange\":{\"f\":\"2015-10-01\",\"l\":\"2016-04-03\"}}")).build();
                        ClientAbstraction client = new ClientBuilderImp().create();
                       
                       
                        ResponseImp resp = (ResponseImp) client.newCall(request).execute();
                        System.out.println("status extract now: "+ resp.responseCode());
                        return resp;
                        } catch (Exception exc) {
                        exc.printStackTrace();
                        return null;
                  }
 
            }`

I tried some other variants in the post body but always returned 400 error.
Appreciate any inputs in this regard.

**Comment by battewr** [comment]
At a glance it looks like you are missing the "criteria=".

I don't usually use the post body for this end-point honestly; the code I generally use uses a blank post body and the url path query string as follows:
`String requestBody = "";
String criteria = OAuth.percentEncode("{\"dateRange\":{\"c\":\"G\",\"r\":\"CUSTOM\",\"f\":\"2015-11-10\",\"l\":\"2015-11-13\"}}");
body = invokPostEndpoint(_client, "https://portal2.foreseeresults.com/services/clients/{clientid}/measures/{targetmeasureid}/respondentsextract?criteria=" + criteria, requestBody);
_logger.info(body);`

**Comment by taruntrehan** [comment]
Hi,
I tried the POST call changes suggested in your response. However, the response code 400 is received.
I think, the endpoint needs POST call in a specific format with parameters specified in body of the request and application content type set accordingly.
Attaching a source code i tried today : 

`private static ResponseImp getRespondentExtr(AcsApiClient apiClient) {
            try {
                  String criteria = OAuth.percentEncode("{\"dateRange\":{\"c\":\"G\",\"r\":\"CUSTOM\",\"f\":\"2015-11-10\",\"l\":\"2015-11-13\"}}");
                  String postTarget = "https://portal2.foreseeresults.com/services/clients/CLIENTID/measures/MEASUREID/respondentsextract?criteria="+criteria;
                  System.out.println("Post Taget URL-"+postTarget);
                  String authorizeSignature = apiClient.getSignedUrl(OAuthMessage.POST, postTarget);
                  RequestAbstraction request = new RequestBuilderImp().builder().withUrl(postTarget)
                          .withHeader("Authorization", authorizeSignature).build();
                  ClientAbstraction client = new ClientBuilderImp().create();
                  ResponseImp resp = (ResponseImp) client.newCall(request).execute();
                  return resp;
            } catch (Exception exc) {
                  exc.printStackTrace();
                  return null;
            }
      }`
 
Please provide your inputs.

**Comment by taruntrehan** [comment]
Hi,
I tried the POST call changes suggested in your response. However, the response code 400 is received.
I think, the endpoint needs POST call in a specific format with parameters specified in body of the request and application content type set accordingly.
Attaching a source code i tried today :


```
private static ResponseImp getRespondentExtr(AcsApiClient apiClient) {
            try {
                  String criteria = OAuth.percentEncode("{\"dateRange\":{\"c\":\"G\",\"r\":\"CUSTOM\",\"f\":\"2015-11-10\",\"l\":\"2015-11-13\"}}");
                  String postTarget = "https://portal2.foreseeresults.com/services/clients/CLIENTID/measures/MEASUREID/respondentsextract?criteria="+criteria;
                  System.out.println("Post Taget URL-"+postTarget);
                  String authorizeSignature = apiClient.getSignedUrl(OAuthMessage.POST, postTarget);
                  RequestAbstraction request = new RequestBuilderImp().builder().withUrl(postTarget)
                          .withHeader("Authorization", authorizeSignature).build();
                  ClientAbstraction client = new ClientBuilderImp().create();
                  ResponseImp resp = (ResponseImp) client.newCall(request).execute();
                  return resp;
            } catch (Exception exc) {
                  exc.printStackTrace();
                  return null;
            }
      }

```

Please provide your inputs.

**Comment by battewr** [comment]
Hi,

At a glance what looks wrong is the missing withPostBody("").  While the post body must be empty, it still must exist for the api to sign the request properly I believe.

**Comment by battewr** [comment]
Confirmed with code sample sent today; the two fixes above fixed the problem.  Sent the entire sample back via email.

**Comment by taruntrehan** [comment]
Thanks for help with this. Really appreciate it.
The two suggestions related to post body and criteria encoding helped together.
On another note, Adding a sample post call code snippet to the repository would be beneficial to other users. Considering POST calls can be tricky; readers in future can save time.
Once a again, thanks for all help. :)
